package io.limberapp.exception.user

import io.limberapp.exception.EntityNotFound

class UserNotFound : EntityNotFound("User")
