package limber.exception.organizationAuth

import limber.exception.UnprocessableException

internal class OrganizationAuthDoesNotExist : UnprocessableException("Organization auth does not exist.")
