package io.limberapp.module.users.exception.user

import io.limberapp.exception.EntityNotFound

class UserNotFound : EntityNotFound("User")
