package io.limberapp.backend.module.users.exception.account

import io.limberapp.exception.notFound.EntityNotFound

internal class UserNotFound : EntityNotFound("User")
